import { PGlite } from '../../mobile/node_modules/@electric-sql/pglite/dist/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage,public to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,created_at timestamptz default now());
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;`);
for (const file of ['202609160001_initial.sql','202609160002_app_operations.sql','202609160003_upload_limits.sql','202609160004_categories.sql']) await db.exec(fs.readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));
const admin='11111111-1111-4111-8111-111111111111', a='22222222-2222-4222-8222-222222222222',b='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${admin}','admin@example.test','{}'),('${a}','a@example.test','{"name":"Candidate A"}'),('${b}','b@example.test','{}'); insert into public.staff_roles values('${admin}','admin');`);
async function as(role,id='') {await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]); await db.exec('set role '+role);}
async function rejects(sql,params=[]) {await assert.rejects(db.query(sql,params));}
await as('authenticated',a);
assert.equal((await db.query('select * from profiles')).rows.length,1);
await rejects("insert into staff_roles values($1,'admin')",[a]);
await rejects("update profiles set email='fake@test'");
await rejects("select write_catalog(1,'delete','{}')");
const job={id:'test-job',title:'Test job',company:'Example',city:'City',country:'Romania',salary:'1000',category:'Manufacturing',description:'Description',hours:'40',accommodation:'Included',benefits:'Provided',contract:'Full-time',openings:2,requirements:['Experience'],icon:'business-outline',status:'draft',featured:false};
await as('authenticated',admin);
await db.query("select write_catalog(1,'create',$1)",[JSON.stringify(job)]);
await as('anon'); assert.equal((await db.query('select read_catalog() as c')).rows[0].c.jobs.length,0); await rejects('select * from profiles');
await as('authenticated',admin);
await rejects("select write_catalog(1,'update',$1)",[JSON.stringify({...job,status:'published'})]);
await db.query("select write_catalog(2,'update',$1)",[JSON.stringify({...job,status:'published',featured:true})]);
await db.query("select write_catalog(3,'create',$1)",[JSON.stringify({...job,id:'other-job',status:'published',featured:true})]);
assert.equal((await db.query('select * from jobs where featured')).rows.length,1);
await as('authenticated',a);
await db.query('insert into applications(customer_id,job_id) values($1,$2)',[a,job.id]);
await rejects('insert into applications(customer_id,job_id) values($1,$2)',[b,job.id]);
await db.exec("update applications set status='Shortlisted'");
assert.equal((await db.query('select status,job_title from applications')).rows[0].status,'Submitted');
assert.equal((await db.query('select job_title from applications')).rows[0].job_title,'Test job');
await as('authenticated',b); assert.equal((await db.query('select * from applications')).rows.length,0);
await as('authenticated',admin); assert.equal((await db.query('select * from applications')).rows.length,1);
const day=(await db.query("select d::date::text as d from generate_series(current_date+1,current_date+7,interval '1 day') d where extract(isodow from d)<6 limit 1")).rows[0].d;
await as('authenticated',a);
const booking=(await db.query("insert into appointments(customer_id,office,date,time,reason) values($1,'Colombo HQ',$2,'09:00','Other Inquiry') returning id",[a,day])).rows[0].id;
await as('authenticated',b);
await rejects("insert into appointments(customer_id,office,date,time,reason) values($1,'Colombo HQ',$2,'09:00','Other Inquiry')",[b,day]);
await rejects('select cancel_appointment($1)',[booking]);
await as('authenticated',a); await db.query('select cancel_appointment($1)',[booking]);
await as('authenticated',b); await db.query("insert into appointments(customer_id,office,date,time,reason) values($1,'Colombo HQ',$2,'09:00','Other Inquiry')",[b,day]);
await as('authenticated',a);
await db.query("insert into storage.objects(bucket_id,name,metadata) values('candidate-documents',$1,'{\"size\":10}')",[a+'/CV/11111111-1111-4111-8111-111111111111-resume.pdf']);
assert.equal((await db.query('select * from list_documents()')).rows[0].name,'resume.pdf');
await as('authenticated',b); assert.equal((await db.query('select * from list_documents()')).rows.length,0);
await as('authenticated',admin); assert.equal((await db.query('select * from list_documents()')).rows.length,1);
await as('authenticated',a);
await rejects("select manage_category((select revision from app_settings),'create','Construction',null)");
await as('authenticated',admin);
const rev=(await db.query('select revision from app_settings')).rows[0].revision;
await db.query("select manage_category($1,'create','Construction',null)",[rev]);
await rejects("select manage_category($1,'create','Other',null)",[rev]);
await rejects("select manage_category($1,'delete','Manufacturing',null)",[Number(rev)+1]);
await db.query("select manage_category($1,'rename','Factory work','Manufacturing')",[Number(rev)+1]);
assert.equal((await db.query('select category from jobs limit 1')).rows[0].category,'Factory work');
await as('anon');
assert.ok((await db.query('select read_catalog() as c')).rows[0].c.categories.includes('Construction'));
await db.close(); console.log('PASS: migrations, profile isolation, role protection, draft visibility, stale saves, featured replacement, application ownership/snapshots, booking conflicts/cancellation, private document metadata');


